const products=[
{id:"bacon",name:"Brasa Bacon",cat:"Burgers",price:38.90,img:"/products/brasa-bacon.webp?v=2",badge:"Mais pedido",desc:"Pão brioche tostado, blend 160g, cheddar, bacon crocante, cebola caramelizada e molho Brasa.",remove:["Cheddar","Bacon","Cebola caramelizada","Molho Brasa"]},
{id:"costela",name:"Burger de Costela",cat:"Burgers",price:42.90,img:"/products/burger-costela.webp?v=2",badge:"Chef indica",desc:"Burger de costela 180g, queijo prato, picles artesanal, crispy de cebola e barbecue defumado.",remove:["Queijo prato","Picles","Crispy de cebola","Barbecue"]},
{id:"xbacon",name:"X-Bacon da Brasa",cat:"Burgers",price:32.90,img:"/products/x-bacon-brasa.webp?v=2",badge:"Promoção",desc:"Blend 150g, queijo, bacon, alface, tomate e maionese artesanal no pão brioche.",remove:["Queijo","Bacon","Alface","Tomate","Maionese"]},
{id:"salad",name:"Brasa Salad",cat:"Burgers",price:31.90,img:"/products/brasa-salad.webp?v=2",badge:"Novidade",desc:"Blend 150g, queijo prato, alface crocante, tomate, cebola roxa e molho verde da casa.",remove:["Queijo prato","Alface","Tomate","Cebola roxa","Molho verde"]},
{id:"batata",name:"Batata Brasa",cat:"Acompanhamentos",price:24.90,img:"https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85",badge:"Crocante",desc:"Batata rústica crocante, páprica defumada, sal de ervas e molho Brasa.",remove:["Páprica","Sal de ervas","Molho Brasa"]},
{id:"combo",name:"Combo Brasa Bacon",cat:"Combos",price:54.90,img:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85",badge:"Economize R$ 9,80",desc:"Brasa Bacon + Batata P + refrigerante lata 350ml.",remove:["Cebola caramelizada","Molho Brasa"]},
{id:"cola",name:"Refrigerante 350ml",cat:"Bebidas",price:7.90,img:"https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=85",badge:"Gelado",desc:"Escolha entre cola, cola zero, guaraná ou laranja.",remove:[]},
{id:"brownie",name:"Brownie na Brasa",cat:"Sobremesas",price:18.90,img:"https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=85",badge:"Final feliz",desc:"Brownie intenso de chocolate, caramelo âmbar e creme gelado de baunilha.",remove:["Caramelo","Creme de baunilha"]}
];
const extras=[["Bacon extra",6.0],["Cheddar extra",5.0],["Burger 160g",12.0],["Molho Brasa",3.0],["Cebola caramelizada",4.0]];
const money=v=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let cart=JSON.parse(localStorage.getItem("brasaCart")||"[]");
let coupon=localStorage.getItem("brasaCoupon")==="BRASA15";
let selected=null,qty=1,mode="delivery",step=1;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function renderProducts(cat="Todos"){
 const grid=$("#productGrid"); grid.innerHTML="";
 const q=(document.querySelector("#storeSearch")?.value||"").trim().toLowerCase();
 const filtered=products.filter(p=>(cat==="Todos"||p.cat===cat)&&(!q||`${p.name} ${p.desc} ${p.cat}`.toLowerCase().includes(q)));
 const menuCount=document.querySelector("#menuCount"); if(menuCount) menuCount.textContent=`${filtered.length} itens`;
 filtered.forEach(p=>{grid.insertAdjacentHTML("beforeend",`<article class="product-card" data-id="${p.id}"><div class="product-image"><img src="${p.img}" alt="${p.name}" onerror="this.onerror=null;this.src='https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=88'"><span class="product-badge">${p.badge}</span></div><div class="product-body"><span class="product-category">${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add-round" aria-label="Adicionar ${p.name}">+</button></div></div></article>`)});
 $$(".product-card").forEach(card=>card.onclick=()=>openProduct(card.dataset.id));
}
function openProduct(id){selected=products.find(p=>p.id===id);qty=1;$("#modalImage").src=selected.img;$("#modalName").textContent=selected.name;$("#modalCat").textContent=selected.cat.toUpperCase();$("#modalDesc").textContent=selected.desc;$("#modalBase").textContent=money(selected.price);$("#qtyValue").textContent=qty;$("#notes").value="";$("#extrasOptions").innerHTML=extras.map(e=>`<div class="check-option"><label><input type="checkbox" class="extra" data-price="${e[1]}" value="${e[0]}"> ${e[0]}</label><b>+ ${money(e[1])}</b></div>`).join("");$("#removeOptions").innerHTML=selected.remove.length?selected.remove.map(r=>`<div class="check-option"><label><input type="checkbox" class="remove" value="${r}"> Sem ${r}</label></div>`).join(""):`<small style="color:var(--muted)">Sem ingredientes removíveis neste item.</small>`;$$('.extra').forEach(x=>x.onchange=()=>{let checked=$$('.extra:checked');if(checked.length>3)x.checked=false;calcModal()});calcModal();$("#productModal").classList.add("open");$("#backdrop").classList.add("show")}
function calcModal(){if(!selected)return;let x=$$(".extra:checked").reduce((s,e)=>s+Number(e.dataset.price),0);$("#modalTotal").textContent=money((selected.price+x)*qty)}
$("#qtyMinus").onclick=()=>{qty=Math.max(1,qty-1);$("#qtyValue").textContent=qty;calcModal()};$("#qtyPlus").onclick=()=>{qty=Math.min(10,qty+1);$("#qtyValue").textContent=qty;calcModal()};
$("#addToCart").onclick=()=>{let x=$$(".extra:checked").map(e=>({name:e.value,price:Number(e.dataset.price)}));let rem=$$(".remove:checked").map(e=>e.value);cart.push({uid:Date.now(),id:selected.id,name:selected.name,img:selected.img,base:selected.price,qty,extras:x,remove:rem,notes:$("#notes").value});saveCart();closeProduct();openCart()};
function closeProduct(){$("#productModal").classList.remove("open");if(!$("#cartDrawer").classList.contains("open"))$("#backdrop").classList.remove("show")}
$("#closeProduct").onclick=closeProduct;
function saveCart(){localStorage.setItem("brasaCart",JSON.stringify(cart));renderCart()}
function totals(){let subtotal=cart.reduce((s,i)=>s+(i.base+i.extras.reduce((a,e)=>a+e.price,0))*i.qty,0);let discount=coupon?subtotal*.15:0;let fee=mode==="pickup"?0:{Centro:6.9,Jardins:8.9,"Vila Nova":5.9}[$("#bairro")?.value||"Centro"];return {subtotal,discount,fee,total:subtotal-discount+fee}}
function renderCart(){const c=$("#cartItems");$("#cartCount").textContent=cart.reduce((s,i)=>s+i.qty,0);if($("#mobileCartCount"))$("#mobileCartCount").textContent=`${cart.reduce((s,i)=>s+i.qty,0)} itens`;if(!cart.length)c.innerHTML=`<div class="empty-cart">🍔<b>Seu carrinho está vazio</b>Adicione algo irresistível do cardápio.</div>`;else c.innerHTML=cart.map(i=>`<div class="cart-item"><img src="${i.img}" alt=""><div><h4>${i.qty}× ${i.name}</h4><small>${i.extras.map(e=>e.name).join(", ")||"Sem adicionais"}</small><br><button data-remove="${i.uid}">Remover</button></div><b>${money((i.base+i.extras.reduce((a,e)=>a+e.price,0))*i.qty)}</b></div>`).join("");$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(i=>i.uid!=b.dataset.remove);saveCart()});let t=totals();$("#subtotal").textContent=money(t.subtotal);$("#discount").textContent="− "+money(t.discount);$("#fee").textContent=mode==="pickup"?"Grátis":money(t.fee);$("#total").textContent=money(t.total);if($("#mobileCartTotal"))$("#mobileCartTotal").textContent=money(t.total)}
function openCart(){$("#cartDrawer").classList.add("open");$("#cartDrawer").setAttribute("aria-hidden","false");$("#backdrop").classList.add("show")}
function closeCart(){$("#cartDrawer").classList.remove("open");$("#cartDrawer").setAttribute("aria-hidden","true");if(!$("#productModal").classList.contains("open"))$("#backdrop").classList.remove("show")}
$("#openCart").onclick=openCart;if($("#mobileCart"))$("#mobileCart").onclick=openCart;$("#closeCart").onclick=closeCart;$("#backdrop").onclick=()=>{closeCart();closeProduct()};
$("#applyCoupon").onclick=()=>{if($("#couponInput").value.trim().toUpperCase()==="BRASA15"){coupon=true;localStorage.setItem("brasaCoupon","BRASA15");$("#couponInput").value="BRASA15 ✓";renderCart()}else{$("#couponInput").value="Cupom inválido";setTimeout(()=>$("#couponInput").value="",1200)}};
$$(".cat").forEach(b=>b.onclick=()=>{$$(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts(b.dataset.cat)});
function checkoutOpen(){if(!cart.length){openCart();return}closeCart();$("#checkout").classList.add("open");step=1;renderStep()}
$("#checkoutBtn").onclick=checkoutOpen;$("#closeCheckout").onclick=()=>$("#checkout").classList.remove("open");
function renderStep(){$$(".step-pane").forEach(p=>p.classList.toggle("active",Number(p.dataset.pane)===step));$$(".steps span").forEach(s=>s.classList.toggle("active",Number(s.dataset.step)<=step));$("#prevStep").style.visibility=step===1?"hidden":"visible";$("#nextStep").textContent=step===4?"Confirmar pedido 🔥":"Continuar →";if(step===4){let t=totals();$("#reviewBox").innerHTML=`<div class="review-line"><span>Cliente</span><b>${$("#cName").value}</b></div><div class="review-line"><span>Recebimento</span><b>${mode==="pickup"?"Retirada grátis":$("#bairro").value}</b></div><div class="review-line"><span>Itens</span><b>${cart.reduce((s,i)=>s+i.qty,0)}</b></div><div class="review-line"><span>Desconto</span><b>− ${money(t.discount)}</b></div><div class="review-line"><span>Total</span><b>${money(t.total)}</b></div>`}}
$("#nextStep").onclick=async()=>{if(step<4){step++;renderStep();return}try{const online=await window.BrasaSupabase?.init();if(!online){$("#checkout").classList.remove("open");$("#tracking").classList.add("open");cart=[];saveCart();return}const session=await BrasaSupabase.session();if(!session){sessionStorage.setItem("brasaReturnCheckout","1");location.href="/login?return=/";return}$("#nextStep").disabled=true;$("#nextStep").textContent="Enviando pedido…";const areaRows=await BrasaSupabase.listAreas();const selectedArea=areaRows.find(a=>a.name===$("#bairro").value);const payload={idempotency_key:crypto.randomUUID(),delivery_mode:mode,delivery_area_id:mode==="delivery"?(selectedArea?.id||null):null,customer:{name:$("#cName").value.trim(),phone:$("#cPhone").value.trim(),email:$("#cEmail").value.trim(),address:mode==="delivery"?document.querySelector("#deliveryFields input")?.value||"":null,neighborhood:mode==="delivery"?$("#bairro").value:null},payment_method:document.querySelector(".pay.active span")?.textContent||"Pix",coupon_code:coupon?"BRASA15":null,items:cart.map(i=>({product_id:i.id,quantity:i.qty,notes:i.notes||"",addon_option_ids:(i.extras||[]).map(e=>e.id).filter(Boolean)}))};const result=await BrasaSupabase.createOrder(payload);if(!result?.ok)throw new Error(result?.error||"Não foi possível criar o pedido.");$("#checkout").classList.remove("open");$("#tracking").classList.add("open");const label=document.querySelector(".tracking-card>small");if(label)label.textContent=`PEDIDO #${result.public_number}`;cart=[];saveCart()}catch(err){alert(err.message||"Erro ao finalizar pedido.")}finally{$("#nextStep").disabled=false;$("#nextStep").textContent="Confirmar pedido 🔥"}};
$("#prevStep").onclick=()=>{if(step>1){step--;renderStep()}};$$(".toggle-choice button").forEach(b=>b.onclick=()=>{$$(".toggle-choice button").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.mode;$("#deliveryFields").style.display=mode==="delivery"?"grid":"none";renderCart()});$("#bairro").onchange=renderCart;$$(".pay").forEach(b=>b.onclick=()=>{$$(".pay").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("#trackBtn").onclick=()=>$("#tracking").classList.add("open");$("#closeTracking").onclick=()=>$("#tracking").classList.remove("open");
(async function bootBrasa(){try{const online=await window.BrasaSupabase?.init();if(online){const remote=await BrasaSupabase.listProducts();if(remote?.length){const curated={"brasa bacon":"/products/brasa-bacon.webp?v=2","burger de costela":"/products/burger-costela.webp?v=2","x-bacon da brasa":"/products/x-bacon-brasa.webp?v=2","brasa salad":"/products/brasa-salad.webp?v=2"};const curatedBadges={"brasa bacon":"Mais pedido","burger de costela":"Chef indica","x-bacon da brasa":"Promoção","brasa salad":"Novidade"};products.splice(0,products.length,...remote.map((p,index)=>({id:p.id,name:p.name,cat:p.categories?.name||"Cardápio",price:Number(p.promotional_price||p.price),img:curated[String(p.name||"").toLowerCase()]||p.image_url||["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=88","https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=85","https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85"][index%3],badge:curatedBadges[String(p.name||"").toLowerCase()]||(p.featured?"Destaque":"Brasa"),desc:p.description||"",remove:[]})))}}}catch(err){console.warn("Usando dados locais:",err)}renderProducts();renderCart()})();
const storeSearch=document.querySelector("#storeSearch");if(storeSearch)storeSearch.addEventListener("input",()=>{const active=document.querySelector(".cat.active");renderProducts(active?.dataset.cat||"Todos")});
