const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const state={page:'overview',data:{orders:[],products:[],categories:[],addons:[],coupons:[],areas:[],banners:[]},role:null};
const labels={overview:'VISÃO GERAL',orders:'PEDIDOS',bot:'ATENDIMENTO IA',products:'PRODUTOS',categories:'CATEGORIAS',addons:'ADICIONAIS',coupons:'CUPONS',delivery:'ÁREAS DE ENTREGA',banners:'BANNERS E PROMOÇÕES',settings:'CONFIGURAÇÕES'};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function statusLabel(s){return ({received:'Novo',confirmed:'Confirmado',preparing:'Em preparação',out_for_delivery:'Em entrega',delivered:'Entregue',cancelled:'Cancelado',rejected:'Recusado'}[s]||s||'Novo')}
function statusClass(s){if(['received'].includes(s))return'new';if(['preparing','out_for_delivery'].includes(s))return'prep';if(['delivered','confirmed'].includes(s))return'ok';return'new'}
function nav(page){state.page=page;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageTitle').textContent=labels[page]||page.toUpperCase();render()}
function overview(){const d=state.data,orders=d.orders||[];const today=new Date().toISOString().slice(0,10);const todays=orders.filter(o=>String(o.created_at||'').startsWith(today));const source=todays.length?todays:orders;const revenue=source.filter(o=>!['cancelled','rejected'].includes(o.status)).reduce((s,o)=>s+Number(o.total||0),0);const waiting=orders.filter(o=>o.status==='received').length;const prep=orders.filter(o=>o.status==='preparing').length;return `<section class="hero"><div><small>RESUMO DO DIA</small><h2>Boa noite, Odilon.</h2><p>Painel conectado ao banco da homologação.</p></div><div class="status-live">● dados em tempo real</div></section><div class="metrics"><div class="metric"><small>Pedidos</small><b>${source.length}</b></div><div class="metric"><small>Novos</small><b>${waiting}</b></div><div class="metric"><small>Em preparo</small><b>${prep}</b></div><div class="metric"><small>Faturamento</small><b>${money(revenue)}</b></div></div><section class="panel"><div class="panel-head"><h3>Pedidos recentes</h3><button class="btn" onclick="nav('orders')">Ver todos</button></div>${orders.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Status</th><th>Tipo</th><th>Total</th><th>Horário</th></tr></thead><tbody>${orders.slice(0,8).map(o=>`<tr><td><b>#${esc(o.public_number)}</b></td><td>${esc(o.customer_name)}</td><td><span class="pill ${statusClass(o.status)}">${statusLabel(o.status)}</span></td><td>${o.delivery_mode==='pickup'?'Retirada':'Entrega'}</td><td>${money(o.total)}</td><td>${new Date(o.created_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Nenhum pedido ainda. Faça um pedido pela loja para vê-lo aqui.</div>`}</section>`}
function orders(){const groups=[['received','Novos'],['confirmed','Confirmados'],['preparing','Em preparação'],['out_for_delivery','Em entrega']];return `<section class="hero"><div><small>OPERAÇÃO</small><h2>Pedidos</h2><p>Acompanhe o fluxo da cozinha e entrega.</p></div></section><div class="kanban">${groups.map(([key,title])=>{const arr=state.data.orders.filter(o=>o.status===key);return `<div class="kanban-col"><h3>${title} • ${arr.length}</h3>${arr.map(o=>`<div class="order-card"><b>#${esc(o.public_number)}</b><small>${esc(o.customer_name||'Cliente')} • ${o.delivery_mode==='pickup'?'Retirada':'Entrega'}</small><strong>${money(o.total)}</strong>${key!=='out_for_delivery'?`<button class="btn" style="width:100%;margin-top:9px" onclick="advanceOrder('${o.id}','${key}')">Avançar status</button>`:''}</div>`).join('')||'<div class="empty">Sem pedidos</div>'}</div>`}).join('')}</div>`}
function products(){const arr=state.data.products||[];return `<section class="hero"><div><small>CARDÁPIO</small><h2>Produtos</h2><p>${arr.length} produtos cadastrados no Supabase.</p></div></section><div class="cards">${arr.map(p=>`<article class="item-card"><img src="${esc(p.image_url||'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85')}" alt="${esc(p.name)}"><div class="body"><small>${esc(p.categories?.name||'Cardápio')}</small><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><strong>${money(p.promotional_price||p.price)}</strong><div style="margin-top:10px"><span class="pill ${p.active&&!p.sold_out?'ok':'new'}">${p.sold_out?'Esgotado':p.active?'Ativo':'Inativo'}</span></div></div></article>`).join('')}</div>`}
function categories(){return tablePage('Categorias','Organize as seções do cardápio',['Nome','Ordem','Status'],(state.data.categories||[]).map(c=>[esc(c.name),c.display_order??0,`<span class="pill ${c.active?'ok':'new'}">${c.active?'Ativa':'Inativa'}</span>`]))}
function addons(){const rows=(state.data.addons||[]).map(a=>[esc(a.name),a.required?'Obrigatório':'Opcional',`${a.min_select||0}–${a.max_select||1}`,`<span class="pill ${a.active?'ok':'new'}">${a.active?'Ativo':'Inativo'}</span>`]);return tablePage('Adicionais','Grupos e opções de personalização',['Grupo','Regra','Seleção','Status'],rows)}
function coupons(){const rows=(state.data.coupons||[]).map(c=>[esc(c.code),c.discount_type==='percentage'?`${c.discount_value}%`:money(c.discount_value),money(c.minimum_order),`${c.usage_count||0}/${c.max_uses||'∞'}`,`<span class="pill ${c.active?'ok':'new'}">${c.active?'Ativo':'Inativo'}</span>`]);return tablePage('Cupons','Descontos válidos na loja',['Código','Desconto','Pedido mínimo','Usos','Status'],rows)}
function delivery(){const rows=(state.data.areas||[]).map(a=>[esc(a.name),money(a.delivery_fee),`${a.additional_minutes||0} min`,money(a.minimum_order),`<span class="pill ${a.active?'ok':'new'}">${a.active?'Ativa':'Inativa'}</span>`]);return tablePage('Áreas de entrega','Taxas e regras por região',['Área','Taxa','Tempo extra','Pedido mínimo','Status'],rows)}
function banners(){const rows=(state.data.banners||[]).map(b=>[esc(b.title),b.starts_at?new Date(b.starts_at).toLocaleDateString('pt-BR'):'Sempre',b.device_scope||'Todos',`<span class="pill ${b.active?'ok':'new'}">${b.active?'Ativo':'Inativo'}</span>`]);return tablePage('Banners e promoções','Campanhas exibidas na loja',['Campanha','Início','Dispositivo','Status'],rows)}
function bot(){return `<section class="hero"><div><small>WHATSAPP + DM CHAMP</small><h2>Atendimento IA</h2><p>Estrutura preparada para consultar o delivery e criar pedidos via WhatsApp.</p></div><div class="status-live">● API preparada</div></section><div class="metrics"><div class="metric"><small>Catálogo</small><b>Online</b></div><div class="metric"><small>Preço e estoque</small><b>API</b></div><div class="metric"><small>Entrega</small><b>API</b></div><div class="metric"><small>Handoff</small><b>Pronto</b></div></div><section class="panel"><div class="panel-head"><h3>Ferramentas do bot</h3></div><div class="settings-grid">${['Consultar catálogo','Consultar produto e adicionais','Calcular taxa de entrega','Validar cupom','Criar pedido com idempotência','Consultar status do pedido','Handoff para humano','Consultar status da loja'].map(x=>`<div class="setting"><b>${x}</b><small>Executado no servidor. O bot nunca define preço ou total.</small></div>`).join('')}</div></section>`}
function settings(){return `<section class="hero"><div><small>CONFIGURAÇÃO</small><h2>Configurações</h2><p>Dados operacionais do Brasa Burger Co.</p></div></section><section class="panel"><div class="settings-grid"><div class="setting"><b>Loja</b><small>Brasa Burger Co. • Rua das Brasas, 147 — Centro</small></div><div class="setting"><b>Horário</b><small>Ter–Dom • 18:00–23:30</small></div><div class="setting"><b>Retirada</b><small>Grátis</small></div><div class="setting"><b>Pagamentos</b><small>Pix, dinheiro, débito e crédito</small></div><div class="setting"><b>Perfil atual</b><small>${esc(state.role||'admin')}</small></div><div class="setting"><b>Segurança</b><small>RLS, Auth e recálculo server-side ativos.</small></div></div></section>`}
function tablePage(title,subtitle,headers,rows){return `<section class="hero"><div><small>GESTÃO</small><h2>${title}</h2><p>${subtitle}</p></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">Nenhum registro</td></tr>`}</tbody></table></div></section>`}
function render(){const f={overview,orders,bot,products,categories,addons,coupons,delivery,banners,settings}[state.page]||overview;$('#pageContent').innerHTML=f()}
async function advanceOrder(id,current){const seq={received:'confirmed',confirmed:'preparing',preparing:'out_for_delivery'};const next=seq[current];if(!next)return;try{await BrasaSupabase.adminUpdateOrderStatus(id,next);const o=state.data.orders.find(x=>x.id===id);if(o)o.status=next;render()}catch(e){alert('Não foi possível atualizar: '+e.message)}}
async function hydrate(){try{const ok=await BrasaSupabase.init();if(!ok)throw new Error('Supabase indisponível');const data=await BrasaSupabase.adminHydrate();state.data=data;state.role=data.role;render()}catch(e){$('#pageContent').innerHTML=`<div class="empty">Não foi possível carregar o painel: ${esc(e.message)}</div>`}}
$$('.nav-item').forEach(b=>b.onclick=()=>{nav(b.dataset.page);$('#sidebar').classList.remove('open');$('#mobileBackdrop').classList.remove('show')});
$('#menuButton').onclick=()=>{$('#sidebar').classList.toggle('open');$('#mobileBackdrop').classList.toggle('show')};$('#mobileBackdrop').onclick=()=>{$('#sidebar').classList.remove('open');$('#mobileBackdrop').classList.remove('show')};
window.nav=nav;window.advanceOrder=advanceOrder;render();hydrate();